name: flutter_rich_editor
description: Flutter Rich Text Editor.
version: 0.0.1
homepage: https://github.com/wxik/flutter-rich-editor

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icon_format_bold.png
    - assets/2.0x/icon_format_bold.png
    - assets/3.0x/icon_format_bold.png
    - assets/icon_format_italic.png
    - assets/2.0x/icon_format_italic.png
    - assets/3.0x/icon_format_italic.png
    - assets/icon_format_link.png
    - assets/2.0x/icon_format_link.png
    - assets/3.0x/icon_format_link.png
    - assets/icon_format_media.png
    - assets/2.0x/icon_format_media.png
    - assets/3.0x/icon_format_media.png
    - assets/icon_format_ol.png
    - assets/2.0x/icon_format_ol.png
    - assets/3.0x/icon_format_ol.png
    - assets/icon_format_ul.png
    - assets/2.0x/icon_format_ul.png
    - assets/3.0x/icon_format_ul.png
